---
- name: Install system packages
  apt:
    pkg: '{{ item }}'
    update_cache: no
  with_items:
    - gcc
    - git
    - python-dev
    - python-pip
    - libpq-dev
    - libsasl2-dev
    - libldap2-dev
    - libffi-dev
    - libssl-dev
  tags:
    - apt

- name: Ensure log directory exists
  file:
    path: '{{ cabot_config.log_path }}'
    state: directory
    mode: 0777

- include: postgres.yml
  when: install_postgres

- name: Install virtualenv
  pip:
    name: virtualenv
  become: True

- name: Install Cabot from pip
  pip:
    name: "cabot=={{ cabot.version }}"
    virtualenv: '{{cabot_config.venv_path}}'
    virtualenv_site_packages: no
  notify: restart cabot

- name: Create config directory
  file:
    path: '/etc/cabot/'
    state: directory
  tags:
    - config

- name: Deploy Cabot config file
  template:
    src: '{{ cabot_config_file_path }}'
    dest: '{{ cabot_config.config_file }}'
    owner: '{{ deploy_user }}'
    mode: 0644
    validate: "/bin/bash -c '. %s'"
  notify: restart cabot
  tags:
    - config

- name: Copy systemd scripts
  template:
    src: templates/{{ item }}.systemd.j2
    dest: /etc/systemd/system/{{ item }}.service
  with_items:
    - cabot
    - cabot-worker
    - cabot-beat
  notify: restart cabot
  tags:
    - systemd

- name: Enable cabot services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: true
  with_items:
    - cabot
    - cabot-worker
    - cabot-beat
  tags:
    - systemd

- name: Start Cabot
  systemd:
    name: cabot
    state: started
    daemon_reload: true
  tags:
    - systemd
