---

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install system packages
  apt:
    pkg: '{{ item }}'
    update_cache: no
  with_items:
    - acl
    - gcc
    - git
    - python-dev
    - python-pip
    - libpq-dev
    - libsasl2-dev
    - libldap2-dev
    - libffi-dev
    - libssl-dev
    - coffeescript
    - node-less
    - redis-server
  tags:
    - apt
  register: apt_redis_result
  changed_when: "'1 not fully installed or removed' in apt_redis_result.stderr"
  failed_when: no

- name: Modify redis.config
  lineinfile:
    path: /etc/systemd/system/redis.service
    regexp: PrivateDevices=yes
    line: PrivateDevices=no

- name: Restart redis service
  systemd:
    state: restarted
    daemon_reload: yes
    name: redis.service

- name: Ensure user exits
  user:
    name: '{{ cabot_user }}'

- name: Ensure log directory exists
  file:
    path: '{{ cabot_log_folder }}'
    state: directory
    owner: '{{ cabot_user }}'
    mode: 0777

- include: postgres.yml
  when: cabot_install_postgres

- name: Install virtualenv
  pip:
    name: virtualenv
  become: yes

- name: Install Cabot from pip
  pip:
    name: 'cabot=={{ cabot_version }}'
    virtualenv: '{{cabot_venv_path}}'
    virtualenv_site_packages: no
  become_user: '{{ cabot_user }}'
  notify: restart cabot
  become: yes

- name: Create config directory
  file:
    path: '{{cabot_config_folder}}'
    state: directory
  tags:
    - config

- name: Deploy Cabot config file
  template:
    src: '{{ cabot_config_template }}'
    dest: '{{ cabot_config_file }}'
    owner: '{{ cabot_user }}'
    mode: 0644
    validate: "/bin/bash -c '. %s'"
  notify: restart cabot
  tags:
    - config

- name: Copy systemd scripts
  template:
    src: templates/{{ item }}.systemd.j2
    dest: /etc/systemd/system/{{ item }}.service
  with_items:
    - cabot
    - cabot-worker
    - cabot-beat
  notify: restart cabot
  tags:
    - systemd

- name: Enable cabot services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: true
  with_items:
    - cabot
    - cabot-worker
    - cabot-beat
  tags:
    - systemd

- name: Start Cabot
  systemd:
    name: cabot
    state: started
    daemon_reload: true
  tags:
    - systemd
