---
- name: Install postgresql
  apt:
    pkg: '{{ item }}'
    update_cache: no
  with_items:
    - postgresql

- name: Install python-psycopg
  pip:
    name: psycopg2
  become: True

- name: Create database user
  postgresql_user:
    name: cabot
    password: cabot
    # role_attr_flags: NOCREATEDB,NOCREATEUSER
    encrypted: yes
    state: present
    fail_on_user: no
  become: yes
  become_user: postgres
  tags:
    - postgres

- name: Create database
  postgresql_db:
    name: index
    owner: cabot
  become: yes
  become_user: postgres
  tags:
    - postgres
